language: node_js

node_js:
  - 10
  - 8
  - 6

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - npm install -g npm@latest

install:
  - npm ci

script:
  - commitlint-travis
  - npm run lint
  - npm test

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: 6

notifications:
  email: false
