language: node_js

cache: yarn

before_script:
  - git fetch --unshallow

script:
  - yarn run commitlint -- --from=HEAD~1
  - yarn test

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true

notifications:
  email: false
