language: node_js

cache: npm

before_install:
  - npm install -g npm

matrix:
  include:
    - node_js: 10
      script:
        - commitlint-travis
        - npm run lint
        - npm run prettier:check
        - npm test
    - node_js: 8
      script: npm test

branches:
  only:
    - master
    - /^v\d+\.\d+.\d+(-\d+)?$/ # e.g. `v3.2.1` | `v3.2.1-0`

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: 8

notifications:
  email: false
