language: node_js

node_js:
  - 10
  - 8
  - 6

cache:
  directories:
    - "$HOME/.npm"

before_install:
  # `npm ci` is available since npm@5.7.0
  - if ruby -e "exit(1) if Gem::Version.new(ARGV[0]) >= Gem::Version.new('5.7.0')" $(npm -v); then
      npm i -g npm@latest;
    fi

script:
  - commitlint-travis
  - npm run lint
  - npm test

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: 6

notifications:
  email: false
