language: node_js

node_js:
  - 9
  - 8
  - 6

cache: yarn

script:
  - commitlint-travis
  - yarn lint
  - yarn test

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: 6

notifications:
  email: false
