language: node_js

node_js:
  - 9
  - 8
  - 6

cache: yarn

before_script:
  - git fetch --unshallow

script:
  - yarn run commitlint --from=HEAD~1
  - yarn lint
  - yarn test

deploy:
  provider: npm
  email: ybiquitous@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true

notifications:
  email: false
