name: npm audit fix

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: ybiquitous/npm-audit-fix-action@add-npm-args
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          npm_args: "--engine-strict=false" # NOTE: Prevent "Unsupported engine" error
